export default {
  INITIAL: 'INITIAL',
  INITIAL_NEXT_BUTTON1: 'INITIAL_NEXT_BUTTON1',
  INITIAL_NEXT_BUTTON2: 'INITIAL_NEXT_BUTTON2',
  INITIAL_NEXT_BUTTON3: 'INITIAL_NEXT_BUTTON3',
  CHOOSE_LOGIN: 'CHOOSE_LOGIN',

  SIGN_UP_BUTTON: 'SIGN_UP_BUTTON',
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_EMAIL: 'SIGN_UP_EMAIL',
  SIGN_UP_PASSWORD: 'SIGN_UP_PASSWORD',
  SIGN_UP_REGISTER_BUTTON: 'SIGN_UP_REGISTER_BUTTON',
};
