export default {
  INITIAL: 'INITIAL',
  INITIAL_NEXT_BUTTON1: 'INITIAL_NEXT_BUTTON1',
  INITIAL_NEXT_BUTTON2: 'INITIAL_NEXT_BUTTON2',
  INITIAL_NEXT_BUTTON3: 'INITIAL_NEXT_BUTTON3',
  CHOOSE_LOGIN: 'CHOOSE_LOGIN',
};
